x-redash-service: &redash-service
  image: redash/redash:10.0.0.b50363
  depends_on:
    - postgres
    - redis
  env_file: ./env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5050:5000"  # 외부 5050 포트 → 내부 Redash 서버 5000포트로 연결
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    command: scheduler

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1

  redis:
    image: redis:7-alpine
    restart: always

  postgres:
    image: postgres:14-alpine
    env_file: ./env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
